- name: Disable Source/Destination check
  uri:
    url: "{{ AUTH_URL_ECS }}/cloudservers/5b2a8b65-bc37-4478-b098-6aabd90645b3"
    method: PUT
    body_format: raw
    follow_redirects: all
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', '../templates/request.json.j2')|to_json }}"
  #when: (not secgroup_id and secgroup_name is defined)
  #register: vpc_router