---
- name: Add private ZooKeeper hosts to inventory
  add_host:
    name: "{{ item }}"
    groups: "private-zk-nodes"
  with_items: "{{ mesos_otc_master }}"

- name: Add public ZooKeeper hosts to inventory
  add_host:
    name: "{{ item }}"
    groups: "public-zk-nodes"
  with_items: "{{ mesos_otc_master }}"

- name: Add new Mesos Master hosts to inventory
  add_host:
    name: "{{ item }}"
    groups: "mesos-masters"
  with_items: "{{ mesos_otc_master }}"
