---
- name: fact_zoo
  set_fact: secfact_zoo="{{ secgrouplistvpc['json']|json_query(query_zoo) }}"
- name: fact_master
  set_fact: secfact_master="{{ secgrouplistvpc['json']|json_query(query_master) }}"
- name: fact_agent
  set_fact: secfact_agent="{{ secgrouplistvpc['json']|json_query(query_agent) }}"
- name: fact_public
  set_fact: secfact_public="{{ secgrouplistvpc['json']|json_query(query_public) }}"