- name: Request asgroup list with search criteria from API
  uri:
    url: "{{ AUTH_URL_VPC }}/autoscaling-api/v1/{{ PROJECT_ID }}/scaling_group"
    method: GET
    return_content: yes
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: asgroups